/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualantiketpesawat;

import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author cacan
 */
public class DataPenumpang extends javax.swing.JFrame {
String[] Judul={"Nama","No. Identitas","Warga Negara","Jenis Kelamin","Alamat","No. Telepon"};
   String[] Field={"namapenumpang","nik","warganegara","jk","alamat","telepon"};
   String SQL ="SELECT*FROM penumpang";
    /**
     * Creates new form DataPenumpang
     */
    public DataPenumpang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        textIdentitas = new javax.swing.JTextField();
        textNegara = new javax.swing.JTextField();
        cbJk = new javax.swing.JComboBox<>();
        textAlamat = new javax.swing.JTextField();
        textTelepon = new javax.swing.JTextField();
        buttonMasuk = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonRefresh = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPenumpang = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Data Penumpang");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("No. Identitas");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel4.setText("Warga Negara");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel6.setText("Alamat");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel7.setText("No. Telepon");

        textNama.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        textIdentitas.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        textNegara.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        cbJk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Kelamin", "Laki-Laki", "Perempuan" }));
        cbJk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJkActionPerformed(evt);
            }
        });

        textAlamat.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        textTelepon.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        buttonMasuk.setBackground(new java.awt.Color(102, 153, 255));
        buttonMasuk.setText(" Masukkan");
        buttonMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMasukActionPerformed(evt);
            }
        });

        buttonUbah.setBackground(new java.awt.Color(102, 153, 255));
        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });

        buttonRefresh.setBackground(new java.awt.Color(102, 153, 255));
        buttonRefresh.setText("Refresh");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });

        buttonHapus.setBackground(new java.awt.Color(255, 102, 102));
        buttonHapus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonHapus.setText("Hapus Data");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        tabelPenumpang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "No. Identitas", "Warga Negara", "Jenis Kelamin", "Alamat", "No. Telepon"
            }
        ));
        tabelPenumpang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPenumpangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPenumpang);

        jButton1.setBackground(new java.awt.Color(102, 255, 153));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/The Noun Project_1.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textNama, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textIdentitas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textNegara, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbJk, javax.swing.GroupLayout.Alignment.TRAILING, 0, 209, Short.MAX_VALUE)
                            .addComponent(textAlamat, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textTelepon, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(buttonMasuk)
                        .addGap(18, 18, 18)
                        .addComponent(buttonUbah)
                        .addGap(18, 18, 18)
                        .addComponent(buttonRefresh)
                        .addGap(0, 105, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textNegara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbJk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonUbah)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonRefresh)
                        .addComponent(buttonMasuk)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonHapus)
                    .addComponent(jButton2)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMasukActionPerformed
         DefaultTableModel model = (DefaultTableModel) tabelPenumpang.getModel();
        if (textNama.getText().trim().equals("")){
 JOptionPane.showMessageDialog(null, "Nama Belum diisi");
 textNama.requestFocus();
 }else if (textIdentitas.getText().trim().equals("")){
 JOptionPane.showMessageDialog(null, "No Penerbangan Belum diisi");
 textIdentitas.requestFocus();
 }else if (textNegara.getText().trim().equals("")){
 JOptionPane.showMessageDialog(null, "Warga Negara Belum diisi");
 textNegara.requestFocus();
 }else if (cbJk.getSelectedItem().toString().equals("")){
 JOptionPane.showMessageDialog(null, " Belum diisi");
 cbJk.requestFocus();
 }else if (textAlamat.getText().trim().equals("")){
 JOptionPane.showMessageDialog(null, "Alamat Belum diisi");
 textAlamat.requestFocus();
 }else if (textTelepon.getText().trim().equals("")){
 JOptionPane.showMessageDialog(null, "No. Telepon Belum diisi");
 textTelepon.requestFocus();
 }else{
     String[] field ={"namapenumpang","nik","warganegara","jk","alamat","telepon"};
     String[] isi ={textNama.getText(),textIdentitas.getText(),textNegara.getText(),cbJk.getSelectedItem().toString(),
         textAlamat.getText(),textTelepon.getText()};
 new Koneksi().SimpanDinamis("penumpang", field, isi);
 new Koneksi().settingJudulTabel(tabelPenumpang, Judul);
 new Koneksi().tampilTabel(tabelPenumpang, SQL, Judul);
 }
        model.addRow(new Object[]{textNama.getText(),textIdentitas.getText(),textNegara.getText(),cbJk.getSelectedItem().toString(),
         textAlamat.getText(),textTelepon.getText()});
    }//GEN-LAST:event_buttonMasukActionPerformed

    private void tabelPenumpangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPenumpangMouseClicked
         int row = tabelPenumpang.getSelectedRow();
        textNama.setText(tabelPenumpang.getModel().getValueAt(row,0).toString());
        textIdentitas.setText(tabelPenumpang.getModel().getValueAt(row,1).toString());
        textNegara.setText(tabelPenumpang.getModel().getValueAt(row,2).toString());
        cbJk.setSelectedItem(tabelPenumpang.getModel().getValueAt(row,3).toString());
        textAlamat.setText(tabelPenumpang.getModel().getValueAt(row,4).toString());
        textTelepon.setText(tabelPenumpang.getModel().getValueAt(row,5).toString());
    }//GEN-LAST:event_tabelPenumpangMouseClicked

    private void cbJkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJkActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        try {
            String[] field = {"namapenumpang","nik","warganegara","jk","alamat","telepon"};
            String[] isi = {textNama.getText(),textIdentitas.getText(),textNegara.getText(),cbJk.getSelectedItem().toString(),
         textAlamat.getText(),textTelepon.getText()};
            new Koneksi().UbahDinamis("penumpang", "namapenumpang", textNama.getText(), field, field);
            JOptionPane.showMessageDialog(null, "Data Berhasil di Edit");
            new Koneksi().settingJudulTabel(tabelPenumpang, Judul);
            new Koneksi().tampilTabel(tabelPenumpang, SQL, Judul);
        } catch (Exception e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed
        textNama.setText("");
        textIdentitas.setText("");
        textNegara.setText("");
        cbJk.setSelectedItem("");
        textAlamat.setText("");
        textTelepon.setText("");
    }//GEN-LAST:event_buttonRefreshActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        new Koneksi().HapusDinamis("penumpang", "namapenumpang", textNama.getText());
        JOptionPane.showMessageDialog(null, "Berhasil Dihapus");
        new Koneksi().settingJudulTabel(tabelPenumpang, Judul);
        new Koneksi().tampilTabel(tabelPenumpang, SQL, Judul);
        textNama.setText("");
        textIdentitas.setText("");
        textNegara.setText("");
        cbJk.setSelectedItem("");
        textAlamat.setText("");
        textTelepon.setText("");
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new Koneksi().tampilLaporan("src/penjualantiketpesawat/penumpang.jrxml","SELECT*FROM penumpang");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new MenuUtama().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPenumpang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPenumpang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPenumpang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPenumpang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPenumpang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonMasuk;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JComboBox<String> cbJk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPenumpang;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textIdentitas;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textNegara;
    private javax.swing.JTextField textTelepon;
    // End of variables declaration//GEN-END:variables
}
